def sweet_dreams
  bpm = 140
  noise_drum = Instrument.new(bpm, NoiseOscillator.new(44100, 123.0, 0.6), nil, nil)
  synth_bass = Instrument.new(bpm, OvertoneAdder.new(SawtoothOscillator.new(44100, 123.0, 0.3), [1.0]), nil, nil)
  voice = Instrument.new(bpm, OvertoneAdder.new(SineOscillator.new(44100, 220.0, 0.8), [0.1, 0.4]), nil, nil)
  
  drum_track = Track.new(noise_drum)
  24.times {
    drum_track.notes << Note.new("", 0, 4)
    drum_track.notes << Note.new("A", 0, 16)
    drum_track.notes << Note.new("", 0, 16)
    drum_track.notes << Note.new("", 0, 8)
  }
  
  bass_track = Track.new(synth_bass)
  6.times {
    bass_track.notes << Note.new("A", 0, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 1, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 2, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 2, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("C", 1, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("C", 2, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 1, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 2, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("F", 0, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("F", 0, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("F", 1, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 2, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("E", 0, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("E", 0, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("E", 1, 16)
    bass_track.notes << Note.new("", 1, 16)
    bass_track.notes << Note.new("A", 2, 16)
    bass_track.notes << Note.new("", 1, 16)
  }
  
  voice_track = Track.new(voice)
  4.times {
    voice_track.notes << Note.new("", 1, 1)
  }
  voice_track.notes << Note.new("", 1, 4)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("", 4, 16)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("", 4, 16)
  voice_track.notes << Note.new("A", 4, 4)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("", 4, 16)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("B", 4, 2)
  
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("A", 4, 8)
  voice_track.notes << Note.new("C", 4, 4)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("A", 4, 16)
  voice_track.notes << Note.new("A", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("A", 4, 16)
  voice_track.notes << Note.new("A", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("D", 4, 4)
  voice_track.notes << Note.new("D", 4, 16)
  voice_track.notes << Note.new("", 4, 16)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("B", 4, 8)
  voice_track.notes << Note.new("", 4, 8)
  voice_track.notes << Note.new("A", 4, 8)
  
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("A", 4, 8)
  voice_track.notes << Note.new("C", 4, 4)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("A", 4, 16)
  voice_track.notes << Note.new("A", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("A", 4, 16)
  voice_track.notes << Note.new("A", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("B", 4, 4)
  voice_track.notes << Note.new("", 4, 4)
  
  voice_track.notes << Note.new("C", 4, 4)
  voice_track.notes << Note.new("A", 4, 8)
  voice_track.notes << Note.new("C", 4, 4)
  voice_track.notes << Note.new("A", 4, 4)
  voice_track.notes << Note.new("A", 4, 8)
  voice_track.notes << Note.new("C", 4, 16)
  voice_track.notes << Note.new("C", 4, 32)
  voice_track.notes << Note.new("", 4, 32)
  voice_track.notes << Note.new("C", 4, 8)
  voice_track.notes << Note.new("D", 4, 8)
  voice_track.notes << Note.new("C", 4, 4)
  voice_track.notes << Note.new("B", 4, 4)

  
  s = Song.new()
  s.tracks = [drum_track, bass_track, voice_track]
  
  return s.next_samples(s.sample_length)
end